export const SET_LAUNDRYREPORT = 'SET_LAUNDRYREPORT';
export const UNMOUNT_LAUNDRYREPORT = 'UNMOUNT_LAUNDRYREPORT';
export const SET_USERREPORT = 'SET_USERREPORT';
export const UNMOUNT_USERREPORT = 'UNMOUNT_USERREPORT';